### PR TITLE
Switch to Maven + Metrics + SimpleSpec

### PR DESCRIPTION
**Pull request by jarreds**
This pull isn't quite ready because I haven't tested metrics yet, and there are some potential perf improvements in metrics usage, but just wanted to get it out there for some feedback.

We also need to get the Java beanstalk API out into a public Maven repo. To get this to build as-is you need to install it locally. Anyone care to tackle that?

### CODE REVIEW

**Comment by cscotta** [comment]
A port of the test suite to SimpleSpec, mavenizing the project, and moving to Metrics? The skies have parted.

There are actually a few things that I really liked about the old Introspector setup that I'd like to find a way to preserve (perhaps a servlet endpoint that would return just the subset of explicitly instrumented stuff rather than the whole metrics JVM shebang, but I can look into that later).

Thanks so much man. Mavenizing the Beanstalk lib should be straightforward -- if someone else hasn't yet (or if it hasn't already been mavenized and pushed to Central in the year or so since I've looked at it), I'm happy to.

Will read over in more detail later, but thanks a ton.

– Scott

**Comment by cscotta** [comment]
I'll check this out in detail this evening -- imagine everything in here's good. If things seem fine, I'll bump the pom to -SNAPSHOT, we can merge it, and keep moving from there.

**Comment by jplock** [comment]
any chance this will get merged in?  we're looking to leverage octobot but I'm a little fearful that it's no longer being updated.  :(

**Comment by cscotta** [comment]
Absolutely! Sorry for the delay in merging this. Glad to see where it's going.

**Comment by cscotta** [comment]
Jarred and Justin,

Moving forward, I'll try to have responses (and ideally merges) done within a day or so of seeing the pull request. Pretty excited by what Jarred's done so far. I expect to be putting in some work here too. Justin, I wouldn't worry too much about inactivity. The project has been stably delivering messages to Android devices at Urban Airship for over a year now. Are there any particular directions you'd like to see the project move in? Feel free to shoot me a message and let me know - love to talk about it!
- Scott

**Pull request merged**
